my.fun <- function(target = NA){
    target <- paste("^", target, "$|-", target, "|", target, "-", sep = "")
    sel <- which(is.na(inc$dpwon.prior)==TRUE); manip <- inc$dpwon.prior[sel] # extract for manipulation
    sel1 <- grep(target, inc$win.long.prior[sel])
    sel2 <- grep(target, inc$win.long      [sel])
    manip[intersect(sel1,sel2)] <- 1 # both
    inc$dpwon.prior[sel] <- manip # return to data after manipulation
}
my.fun("adc")
my.fun("ave")
my.fun("cc1")
my.fun("cp")
my.fun("cpp")
my.fun("dsppn")
my.fun("fc1")
my.fun("fdn")
my.fun("indep")
my.fun("mas")
my.fun("mc")
my.fun("morena")
my.fun("left")
my.fun("npp")
my.fun("pac1")
my.fun("pan")
my.fun("parm")
my.fun("pasd")
my.fun("paz")
my.fun("pcc")
my.fun("pcd1")
my.fun("pcdt")
my.fun("pchu")
my.fun("pcm2")
my.fun("pcp")
my.fun("pcpp")
my.fun("pebc")
my.fun("pec")
my.fun("pes")
my.fun("pfcrn")
my.fun("pfd1")
my.fun("ph")
my.fun("ph_bcs")
my.fun("pj1")
my.fun("pjs")
my.fun("pl1")
my.fun("plm")
my.fun("pmch")
my.fun("pmp")
my.fun("pmr")
my.fun("pmt")
my.fun("pna")
my.fun("poc")
my.fun("ppc")
my.fun("ppg")
my.fun("ppro")
my.fun("pps")
my.fun("pps")
my.fun("ppt")
my.fun("prc")
my.fun("prd")
my.fun("pri")
my.fun("prs")
my.fun("prt")
my.fun("prv")
my.fun("ps1")
my.fun("psd1")
my.fun("psdc")
my.fun("psi")
my.fun("psn")
my.fun("pt")
my.fun("pudc")
my.fun("pup")
my.fun("pvem")
my.fun("pver")
my.fun("si")
my.fun("trans")
my.fun("via_radical")

tmp2 <- inc$dpwon.prior

table(tmp1, tmp2, useNA = "always")
